### ISSUE TITLE
[BUG] With JIRA-Connector API-Builder fails to start

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Builder-Ext/api-builder-extras#16]
**Artefact version you are using**
JIRA Connector 0.0.4

**API-Builder version you are using**
Leeds

**Actual behavior**
API-Builder crashed when having the JIRA-Connector installed.

**Expected behavior**
Installation should succeed. API-Builder should not crash.

**Log-Output in Debug**
```
1587475228616  [@axway/api-builder-plugin-fn-swagger] Loading OpenAPI specs from 'C:\workspaces\API-Builder-Projects\test3\swagger'
1587475228637  [@axway/api-builder-plugin-fn-swagger] Found the following OpenAPI specs: ["jira-cp-connector"]
1587475229134  [@axway/api-builder-plugin-fn-swagger] [jira-cp-connector] There was a problem creating Swagger flow-node from: C:\workspaces\API-Builder-Projects\test3\swagger\jira-cp-connector.json
1587475229136  server failed to start
1587475229137  TypeError: There was a problem loading 'C:\workspaces\API-Builder-Projects\test3\node_modules\@axway\api-builder-plugin-fn-swagger':
Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at stubCredential (C:\workspaces\API-Builder-Projects\test3\node_modules\@axway\api-builder-oas-flow-node\src\plugin\createStubCredentials.js:39:19)
    at createStubCredentials (C:\workspaces\API-Builder-Projects\test3\node_modules\@axway\api-builder-oas-flow-node\src\plugin\createStubCredentials.js:78:16)  
    at generateServiceConfig (C:\workspaces\API-Builder-Projects\test3\node_modules\@axway\api-builder-oas-flow-node\src\plugin\generateServiceConfig.js:182:26) 
    at getPlugin (C:\workspaces\API-Builder-Projects\test3\node_modules\@axway\api-builder-oas-flow-node\src\plugin\index.js:99:7)
    at async resolveModule (C:\workspaces\API-Builder-Projects\test3\node_modules\@axway\api-builder-runtime\lib\plugins.js:79:20)
    at async Object.findPlugins (C:\workspaces\API-Builder-Projects\test3\node_modules\@axway\api-builder-runtime\lib\plugins.js:208:13)
```

**Comment by cwiechmann** [comment]
This is fixed with version 0.0.5
